[project]
name = "earth2studio.recipe.hens"
version = "0.1.0"
description = "Huge Ensembles (HENS) Recipe"
readme = "README.md"
# Restrict to below 3.13 until rapids updates for 3.13
requires-python = ">=3.11,<3.14"
authors = [
  { name="NVIDIA Earth-2 Team" },
]
dependencies = [
    "cartopy>=0.24.1",
    "earth2studio[cyclone,sfno]>=0.9.0",
    "hydra-core>=1.3.0",
    "omegaconf",
    "termcolor>=3.0.1",
]

[project.urls]
Homepage = "https://github.com/NVIDIA/earth2studio/recipes/hens"
Documentation = "https://github.com/NVIDIA/earth2studio/recipes/hens/README.md"
Issues = "https://github.com/NVIDIA/earth2studio/issues"
Changelog = "https://github.com/NVIDIA/earth2studio/blob/main/CHANGELOG.md"

# ==== UV configuration ====
[tool.uv]
# Force onnx to only try to install when below 3.13, otherwise we will use onnx weekly
override-dependencies = ["onnx; python_full_version < '3.13'"]

[tool.uv.sources]
omegaconf = { git = "https://github.com/omry/omegaconf.git" }
earth2studio = { path = "../../", editable = true }

[tool.hatch.build.targets.sdist]
include = ["src/**/*.py"]
exclude = []

[dependency-groups]
dev = [
    "jupytext>=1.17.1",
]
